### ISSUE TITLE
Applying auto-fire hook from the mod "Archers (RPG series)" on Kraken Slayer Crossbow causes crashing when firing after first reload before the second shot

### ISSUE THREAD

**Issue by Postponium** [mariumbacchus/Soulslike-Weaponry#141]
Hello there! Title, basically. Really love both the game and visual design of that Crossbow, wish it could be compatible with that auto-fire upgrade.

Crash report below, if it is relevant. The modpack is Prominence II RPG. Apologies if this is an incorrect channel to report this incompatibility! 

Have a wonderful day.

Time: 2024-07-03 18:28:26
Description: Ticking entity

Time: 2024-07-03 18:28:26
Description: Ticking entity

com.bawnorton.neruina.exception.DoNotHandleException: java.lang.StackOverflowError
	at com.bawnorton.neruina.handler.NeruinaTickHandler.handleEntityTicking(NeruinaTickHandler.java:160)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:121)
	at MC//net.minecraft.world.World.wrapOperation$jmb000$neruina$catchTickingEntities(World.java:14548)
	at MC//net.minecraft.world.World.tickEntity(World.java:480)
	at MC//net.minecraft.client.world.ClientWorld.method_32124(ClientWorld.java:255)
	at MC//net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at MC//net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld.java:251)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1901)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.StackOverflowError
	at java.base@17.0.8/java.util.HashMap.hash(HashMap.java:338)
	at java.base@17.0.8/java.util.HashMap.getNode(HashMap.java:568)
	at java.base@17.0.8/java.util.HashMap.get(HashMap.java:556)
	at MC//net.minecraft.nbt.NbtCompound.getType(NbtCompound.java:279)
	at MC//net.minecraft.nbt.NbtCompound.getList(NbtCompound.java:418)
	at MC//net.minecraft.item.ItemStack.getEnchantments(ItemStack.java:560)
	at MC//net.minecraft.enchantment.EnchantmentHelper.getLevel(EnchantmentHelper.java:71)
	at MC//net.minecraft.item.CrossbowItem.getPullTime(CrossbowItem.java:342)
	at MC//net.minecraft.item.CrossbowItem.getMaxUseTime(CrossbowItem.java:338)
	at net.soulsweaponry.items.ModdedCrossbow.onStoppedUsing(ModdedCrossbow.java:71)
	at MC//net.minecraft.item.ItemStack.onStoppedUsing(ItemStack.java:508)
	at MC//net.minecraft.entity.LivingEntity.stopUsingItem(LivingEntity.java:3169)
	at MC//net.minecraft.client.network.ClientPlayerEntity.stopUsingItem(ClientPlayerEntity.java:16345)
	at MC//net.minecraft.client.network.ClientPlayerInteractionManager.stopUsingItem(ClientPlayerInteractionManager.java:487)
	at MC//net.minecraft.entity.LivingEntity.handler$bee000$archers$asd(LivingEntity.java:13649)
	at MC//net.minecraft.entity.LivingEntity.tickItemStackUsage(LivingEntity.java)
	at MC//net.minecraft.entity.LivingEntity.tickActiveItemStack(LivingEntity.java:3010)
	at MC//net.minecraft.entity.LivingEntity.stopUsingItem(LivingEntity.java:3171)
	at MC//net.minecraft.client.network.ClientPlayerEntity.stopUsingItem(ClientPlayerEntity.java:16345)
	at MC//net.minecraft.client.network.ClientPlayerInteractionManager.stopUsingItem(ClientPlayerInteractionManager.java:487)
	at MC//net.minecraft.entity.LivingEntity.handler$bee000$archers$asd(LivingEntity.java:13649)
	at MC//net.minecraft.entity.LivingEntity.tickItemStackUsage(LivingEntity.java)
	at MC//net.minecraft.entity.LivingEntity.tickActiveItemStack(LivingEntity.java:3010)
	at MC//net.minecraft.entity.LivingEntity.stopUsingItem(LivingEntity.java:3171)
	at MC//net.minecraft.client.network.ClientPlayerEntity.stopUsingItem(ClientPlayerEntity.java:16345)
	at MC//net.minecraft.client.network.ClientPlayerInteractionManager.stopUsingItem(ClientPlayerInteractionManager.java:487)
	(that repeats numerous times) 
	at MC//net.minecraft.entity.LivingEntity.handler$bee000$archers$asd(LivingEntity.java:13649)
	at MC//net.minecraft.entity.LivingEntity.tickItemStackUsage(LivingEntity.java)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.bawnorton.neruina.handler.NeruinaTickHandler.handleEntityTicking(NeruinaTickHandler.java:160)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:121)
	at MC//net.minecraft.world.World.wrapOperation$jmb000$neruina$catchTickingEntities(World.java:14548)
	at MC//net.minecraft.world.World.tickEntity(World.java:480)
	at MC//net.minecraft.client.world.ClientWorld.method_32124(ClientWorld.java:255)
	at MC//net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at MC//net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld.java:251)
Mixins in Stacktrace: None found

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 2124
	Entity Name: Echpochmak
	Entity's Exact location: 12.69, 135.00, 17.71
	Entity's Block location: World: (12,135,17), Section: (at 12,7,1 in 0,8,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at MC//net.minecraft.world.World.tickEntity(World.java:480)
	at MC//net.minecraft.client.world.ClientWorld.method_32124(ClientWorld.java:255)
	at MC//net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at MC//net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld.java:251)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1901)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		com.jozufozu.flywheel.mixin.ClientMainMixin (flywheel.mixins.json)
		org.vivecraft.mixin.client.main.MainMixin (vivecraft.mixins.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['Echpochmak'/2124, l='ClientLevel', x=12.69, y=135.00, z=17.71]]
	Chunk stats: 1024, 380
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,120,0), Section: (at 0,8,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 36580 game time, 36580 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at MC//net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:458)
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2406)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		com.jozufozu.flywheel.mixin.ClientMainMixin (flywheel.mixins.json)
		org.vivecraft.mixin.client.main.MainMixin (vivecraft.mixins.json)

**Comment by mariumbacchus** [comment]
Hi, sorry in advance for late response!
This might be another mod issue since I am seeing a lot of custom libraries being called like this one: `com.bawnorton.neruina.handler.NeruinaTickHandler`. I'll look into it and see if there is anything I can fix about it, but it might be best for the other modders to handle this.

**Comment by mariumbacchus** [comment]
I have updated the mod which changed the code of the bows and crossbows drastically. Hopefully this fixed the incompatibility issue, make another issue post if the error persists!
