### ISSUE TITLE
[BUG]Server reported error

### ISSUE THREAD

**Issue by TW-Black-Cat** [mariumbacchus/Soulslike-Weaponry#197]
server core:Arclight
Minecraft: 1.20.1
forge: 47.2.20
Soulslike-Weaponry: 1.1.4.4d
epic-fight:20.9.2

[01:19:54 ERROR] [STDERR]: java.util.NoSuchElementException: Item Capability Exception: No Item named soulsweapons:holy_moonlight_shortsword
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/epicfight@20.9.2/yesman.epicfight.api.data.reloader.ItemCapabilityReloadListener.apply(ItemCapabilityReloadListener.java:77)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/epicfight@20.9.2/yesman.epicfight.api.data.reloader.ItemCapabilityReloadListener.m_5787_(ItemCapabilityReloadListener.java:48)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
[01:19:54 ERROR] [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[01:19:54 ERROR] [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:783)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:166)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:19:54 ERROR] [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:46)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:13)
[01:19:54 ERROR] [STDERR]:      at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:19:54 ERROR] [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:19:54 ERROR] [STDERR]:      at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
[01:19:54 ERROR] [STDERR]:      at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
[01:19:54 ERROR] [STDERR]: java.util.NoSuchElementException: Item Capability Exception: No Item named soulsweapons:test_item
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/epicfight@20.9.2/yesman.epicfight.api.data.reloader.ItemCapabilityReloadListener.apply(ItemCapabilityReloadListener.java:77)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/epicfight@20.9.2/yesman.epicfight.api.data.reloader.ItemCapabilityReloadListener.m_5787_(ItemCapabilityReloadListener.java:48)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
[01:19:54 ERROR] [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[01:19:54 ERROR] [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:783)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
[01:19:54 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:166)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:19:54 ERROR] [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:46)
[01:19:54 ERROR] [STDERR]:      at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:13)
[01:19:54 ERROR] [STDERR]:      at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:19:54 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:19:54 ERROR] [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:19:54 ERROR] [STDERR]:      at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
[01:19:54 ERROR] [STDERR]:      at io.izzel.arclight.server.Launcher.main(Launcher.java:18)

**Comment by mariumbacchus** [comment]
You can ignore the messages about missing capabilities, I just managed to name the Holy Moonlight Sword's Better Combat file the wrong id, it just notifies you about it. Shouldn't impact your game, I've already fixed this issue for the next update regardless.
