### ISSUE TITLE
Server Crash (latest update 1.19.3 Fabric)

### ISSUE THREAD

**Issue by gamerpotion** [mariumbacchus/Soulslike-Weaponry#3]
Hi, we were using the latest update on my darkrpg modpack server and noticed a server crash you may want to look into, log below
[1.19.3] SW-0.9.8.2 fabric

```---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2023-02-24 18:16:45
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "$$1" is null
	at net.minecraft.class_1937.method_8396(class_1937.java:401)
	at net.soulsweaponry.entity.ai.goal.AccursedLordGoal.handSlamLava(AccursedLordGoal.java:231)
	at net.soulsweaponry.entity.ai.goal.AccursedLordGoal.method_6268(AccursedLordGoal.java:212)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:774)
	at net.minecraft.class_1309.method_6007(class_1309.java:2664)
	at net.minecraft.class_1308.method_6007(class_1308.java:552)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.soulsweaponry.entity.mobs.AccursedLordBoss.method_6007(AccursedLordBoss.java:177)
	at net.minecraft.class_1309.method_5773(class_1309.java:2404)
	at net.minecraft.class_1308.method_5773(class_1308.java:352)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1937.method_8396(class_1937.java:401)
	at net.soulsweaponry.entity.ai.goal.AccursedLordGoal.handSlamLava(AccursedLordGoal.java:231)
	at net.soulsweaponry.entity.ai.goal.AccursedLordGoal.method_6268(AccursedLordGoal.java:212)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:774)
	at net.minecraft.class_1309.method_6007(class_1309.java:2664)
	at net.minecraft.class_1308.method_6007(class_1308.java:552)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.soulsweaponry.entity.mobs.AccursedLordBoss.method_6007(AccursedLordBoss.java:177)
	at net.minecraft.class_1309.method_5773(class_1309.java:2404)
	at net.minecraft.class_1308.method_5773(class_1308.java:352)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)

-- Entity being ticked --
Details:
	Entity Type: soulsweapons:accursed_lord_boss (net.soulsweaponry.entity.mobs.AccursedLordBoss)
	Entity ID: 144840
	Entity Name: The Decaying King
	Entity's Exact location: -1548.08, 33.00, 272.82
	Entity's Block location: World: (-1549,33,272), Section: (at 3,1,0 in -97,2,17; chunk contains blocks -1552,0,272 to -1537,255,287), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,0,0 to -1537,255,511)
	Entity's Momentum: 0.01, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 5 total; [class_3222['hellrezzer'/82028, l='ServerLevel[world]', x=546.28, y=33.00, z=-1137.57], class_3222['FeketeVero45'/47033, l='ServerLevel[world]', x=539.75, y=61.00, z=-1654.92], class_3222['ima44km'/132232, l='ServerLevel[world]', x=-1541.75, y=33.00, z=272.31], class_3222['Elliotak56'/130179, l='ServerLevel[world]', x=116.30, y=54.00, z=1435.40], class_3222['Chaosemperor15'/40234, l='ServerLevel[world]', x=-1537.50, y=33.00, z=288.50]]
	Chunk stats: 7542
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-720,62,6008), Section: (at 0,14,8 in -45,3,375; chunk contains blocks -720,0,6000 to -705,255,6015), Region: (-2,11; contains chunks -64,352 to -33,383, blocks -1024,0,5632 to -513,255,6143)
	Level time: 4691686 game time, 4324647 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 4.15.0-192-generic
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3424684272 bytes (3266 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 3.20
	Number of physical packages: 2
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: G200eR2
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x0534
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 137121.34
	Virtual memory used (MB): 215325.97
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 3495.00
	JVM Flags: 2 total; -Xmx12288M -Xms512M
	Fabric Mods: 
		adabranium: Adabranium 2.4.0+1.19.3
		adorn: Adorn 4.0.1+1.19.3
		advancednetherite: Advanced Netherite 1.6.6-1.19.3
		airchidori: Air Chidori Origin 1.0.0
		alloy_forgery: Alloy Forgery 2.0.19+1.19.3
		amethyst_core: Amethyst Core 1.0.4+1.19.3
		amethyst_imbuement: Amethyst Imbuement 1.19.3-05
			playerabilitylib: Pal 1.7.0
			structurized-reborn: Structurized Reborn 1.19.3-01
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.1.70
		balm-fabric: Balm 5.0.2
		betteradvancements: Better Advancements 0.3.1.149
		bhmenu: BHMenu-Fabric 1.19.3-1.3
		bisecthosting: BisectHosting 1.0.3
		block_limit_fix: Block Limit Fix 1.0.3-fabric
		blockus: Blockus 2.6.2+1.19.3
			terraform-wood-api-v1: Terraform Wood API (v1) 5.0.0-beta.1
		boatoverhaul: BoatOverhaul 2.0.0
		bookshelf: Bookshelf 17.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.5.1-1.19.3
			maelstrom_library: Maelstrom Library 1.4-1.19.3-rc1
			multipart_entities: MultipartEntities 1.3-1.19.3-rc1
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		castleblocks: CastleBlocks 1.21
		cinderscapes: Cinderscapes 3.1.0
			cinderscapes-common: Cinderscapes: Common 3.1.0
			cinderscapes-worldgen: Cinderscapes: World Generation 3.1.0
		clickadv: Clickable Advancements Mod 3.0
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+16
		collective: Collective 6.48
		configured: Configured 2.0.2
		crawl: Crawl 0.11.5
		croptopia: Croptopia 2.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkbindings: DarkBindings - Custom Recipes 1.2.4
		darkcap: DarkCap - Cap Your XP! 1.0.2
		darkflight: DarkFlight - Simple Jetpack 1.0.3
		darkinventory: DarkInventory - Keep Inventory On 1.0.0
		darkloot: DarkLoot - Better Mob Loot 1.0.9
		darkmenu: DarkMenu - DarkRPG Legacy Menu 1.0.2
		darkmining: DarkMining - Better Block Drops 1.0.3
		darkquesting: DarkQuesting - A Quest Mod 1.1.0
		darkrtp: DarkRTP - RTP Teleport 1.0.3
		darkspawn: DarkSpawn - Teleport to Spawn 1.0.0
		darkspins: DarkSpins - XP Casino 1.0.3
		darkstarter: DarkStarter - Starter Items 1.0.0
		darktides: DarkTides - Breathe Underwater 1.0.7
		darkwooly: DarkWooly - Get More Wool 1.0.1
		dawn: Dawn API 4.1.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 5.0.0-beta.1
		diamondeconomy: Diamond Economy 1.5.4
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
		diamondsauctionhouse: Diamond Auction House 1.1.41.19.3
			sgui: sgui 1.2.1+1.19.3
		dragonloot: DragonLoot 1.1.3
		durability101: Durability101 0.0.4
		emerald_tools: Emerald Tools 1.5.7
		enchanting-table-descriptions: Enchanting Table Descriptions 0.1.0+1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		extraalchemy: Extra Alchemy 1.9.2
		extraorigins: Extra Origins 1.19-3
		fabric-api: Fabric API 0.74.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.0+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.14+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.5+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.15
		farsight: Farsight Mod 1.19-3.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		ferritecore: FerriteCore 5.1.0
		foxboi_two: Kitsune 1.1.9
		fzzy_core: Fzzy Core 0.1.2+1.19.3
		gear_core: Gear Core 0.1.3+1.19.3
		gearifiers: Gearifiers 0.1.5+1.19.3
		geckolib: Geckolib 4.0.4
			com_eliotlash_mclib_mclib: mclib 20
		getittogetherdrops: Get It Together, Drops! fabric-1.19.3-1.3
		globalpacks: Global Data- & Resourcepacks 1.15.3_fabric
		goml: Get Off My Lawn ReServed 1.7.0+1.19.3
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			hologram-api: Hologram API 0.2.3+1.19.3
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		handcrafted: Handcrafted 2.0.4
		harvest_scythes: Harvest Scythes 2.5.5+mc1.19.3
			mm: Manningham Mills 2.3
		healingcampfire: Healing Campfire 5.1
		healthcare: Health Care 1.2.1
			config2brigadier: Config to Brigadier 1.2.1
			server_translations_api: Server Translations API 1.4.19+1.19.3
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		immersive_aircraft: Immersive Aircraft 0.3.0+1.19.3
		immersive_armors: Immersive Armors 1.5.4+1.19.3
		ironchests: Iron Chests 1.7.8
			libgui: LibGui 6.5.0+1.19.3
				jankson: Jankson 5.0.0+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		jade: Jade 9.3.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 12.2.0.17
		journeymap: Journeymap 5.9.3
			journeymap-api-fabric: JourneyMap API 1.19.3-1.9-fabric-SNAPSHOT
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		limitedspawners: Limited Spawner 1.0.6
		lithium: Lithium 0.10.4
		lootr: Lootr 0.4.25.65
		magistuarmory: Epic Knights Mod 7.6
		maxhealthfix: MaxHealthFix 9.0.1
		minecraft: Minecraft 1.19.3
		mo_glass: Mo Glass 1.6.1-MC1.19.3
		more_gems: More Gems 1.5.7
			pugh_tools: Pugh Tools 1.4.7
		mythicmetals: Mythic Metals 0.17.2+1.19.3
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19.3
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		mythicmetals_decorations: Mythic Metals Decorations 0.5.2+1.19.3
		mythicupgrades: Mythic Upgrades +fabric-1.6-BetaPreview3-1.19.3
		nochatreports: No Chat Reports 1.19.3-v2.0.0
		nohostilesaroundcampfire: No Hostiles Around Campfire 5.1
		origins: Origins 1.8.1
			apoli: Apoli 2.7.1
				calio: Calio 1.8.0
		origins-classes: Origins: Classes 1.5.0
		owo: oωo 0.10.2+1.19.3
			blue_endless_jankson: jankson 1.2.1
		pack_it_up: Pack It Up! 0.3.0+1.19.3
		painters_blocks_wrapper: Painter's Blocks 2.0.0+1.19.3
			painters_blocks: Painter's Blocks 2.0.0+1.19.3
		pehkui: Pehkui 3.7.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pfm: Paladin's Furniture 1.1.2
		plentyofarmors: Plenty Of Armors 1.0.3
		promenade: Promenade 3.1.0
		redmorestructure: Reds More Structures 1.0.5-fabric-1.19.3
		resourcefullib: Resourceful Lib 1.2.7
			com_teamresourceful_yabn: yabn 1.0.2
		sdlink: Simple Discord Link 2.2.0
		servercore: ServerCore 1.3.4-1.19.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		simple-rpc: Simple RPC 3.2.1
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.2.10
		simplyswords: Simply Swords 1.43.1-1.19.3
		sit: Sit 1.19.3-22
		smoothboot: Smooth Boot 1.19-1.7.1
		smwyg: Show Me What You Got 1.1.0
		soulsweapons: Marium's Soulslike Weaponry 0.9.8
		stacker: Stacker 3.0.2-1.19.3
			stacc: Stacc 1.4.0
		starlight: Starlight 1.1.1+fabric.ae22326
		t_and_t: Towns and Towers 1.10.1
		terrablender: TerraBlender 2.1.0.134
		terrestria: Terrestria 5.1.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 5.0.0-beta.1
			terrestria-common: Terrestria: Common 5.1.1
			terrestria-worldgen: Terrestria: World Generation 5.1.1
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		things: Things 0.3.0+1.19.3
		timeoutout: TimeOut Out 1.0.3+1.19.1
		toofast: TooFast 1.0.0
		toolstats: ToolStats 13.0.1
		traverse: Traverse 6.1.2
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 5.0.0-beta.1
			terraform-config-api-v1: Terraform Config API (v1) 5.0.0-beta.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 5.0.0-beta.1
			terraform-tree-api-v1: Terraform Tree API (v1) 5.0.0-beta.1
			traverse-common: Traverse: Common 6.1.2
			traverse-worldgen: Traverse: World Generation 6.1.2
		trinkets: Trinkets 3.5.1
		universal_shops: Universal Shops 1.1.2+1.19.3
			common-economy-api: Common Economy API 1.0.0
			placeholder-api: Placeholder API 2.0.0-pre.4+1.19.3
			polymer-core: Polymer (Core) 0.3.5+1.19.3
				polymer-networking: Polymer (Networking) 0.3.5+1.19.3
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.3.5+1.19.3
			polymer-resource-pack: Polymer (Resource Pack) 0.3.5+1.19.3
				polymer-common: Polymer (Common) 0.3.5+1.19.3
		vanityslots: Vanity Slots 1.2.5
		waystones: Waystones 12.0.2
		yosbr: YOSBR 0.1.1
	Server Running: true
	Player Count: 39 / 40; [class_3222['_PrapTZ_'/474, l='ServerLevel[world]', x=1556.23, y=126.00, z=-5417.62], class_3222['DeathDoggo5'/476, l='ServerLevel[world]', x=-926.33, y=-30.00, z=5412.66], class_3222['VooDooer7040'/464, l='ServerLevel[world]', x=1812.17, y=71.00, z=8842.92], class_3222['marszeuz'/39828, l='ServerLevel[world]', x=3017.14, y=23.00, z=6586.42], class_3222['Gewuerzwanze'/463, l='ServerLevel[world]', x=4633.89, y=120.00, z=5812.75], class_3222['Come_And_See'/63789, l='ServerLevel[world]', x=-745.63, y=74.00, z=6241.59], class_3222['LincolnsMine'/63919, l='ServerLevel[world]', x=-474.86, y=112.00, z=-2679.59], class_3222['Newking1974'/477, l='ServerLevel[world]', x=3668.11, y=50.88, z=9195.70], class_3222['Leabwa'/6254, l='ServerLevel[world]', x=6606.61, y=107.00, z=10582.37], class_3222['hellrezzer'/82028, l='ServerLevel[world]', x=546.28, y=33.00, z=-1137.57], class_3222['FeketeVero45'/47033, l='ServerLevel[world]', x=539.75, y=61.00, z=-1654.92], class_3222['Hamster124563'/62687, l='ServerLevel[world]', x=1550.83, y=37.00, z=-2278.83], class_3222['Shurimon'/42006, l='ServerLevel[world]', x=-2704.15, y=66.00, z=5361.46], class_3222['ejpgaming55'/98209, l='ServerLevel[world]', x=-1078.62, y=76.00, z=5948.23], class_3222['Chaosemperor15'/40234, l='ServerLevel[world]', x=-1537.50, y=33.00, z=288.50], class_3222['PiouPiou93'/54760, l='ServerLevel[world]', x=-1075.47, y=66.00, z=5142.44], class_3222['Marssumpex9'/26016, l='ServerLevel[world]', x=2.16, y=61.00, z=5.01], class_3222['SnowTheArcticFox'/56635, l='ServerLevel[world]', x=1923.37, y=68.00, z=-1012.27], class_3222['ellothere4'/78672, l='ServerLevel[world]', x=10299.82, y=67.75, z=-5009.51], class_3222['yu2540825244'/67263, l='ServerLevel[world]', x=3505.95, y=113.00, z=-8658.36], class_3222['StarryScienceCat'/470, l='ServerLevel[world]', x=-6425.42, y=-50.72, z=-7564.78], class_3222['OceanBerrie'/82380, l='ServerLevel[world]', x=-7289.82, y=89.00, z=-19942.06], class_3222['Kartton_'/120300, l='ServerLevel[world]', x=-8516.50, y=59.02, z=-6526.25], class_3222['Hxirox'/43408, l='ServerLevel[world]', x=-1167.37, y=59.00, z=5514.48], class_3222['Predator360x'/123679, l='ServerLevel[world]', x=4955.97, y=-4.94, z=7827.71], class_3222['TropicalSam87240'/123690, l='ServerLevel[world]', x=-4378.44, y=63.00, z=4025.00], class_3222['fuzzydino07'/468, l='ServerLevel[world]', x=293.19, y=86.00, z=6672.46], class_3222['Elliotak56'/130179, l='ServerLevel[world]', x=116.30, y=54.00, z=1435.40], class_3222['ima44km'/132232, l='ServerLevel[world]', x=-1541.75, y=33.00, z=272.31], class_3222['littedemon9141'/106205, l='ServerLevel[world]', x=2852.80, y=86.00, z=-783.79], class_3222['Aikanaro89s'/53188, l='ServerLevel[world]', x=-8405.61, y=63.00, z=-8214.85], class_3222['RedRobedRider'/139179, l='ServerLevel[world]', x=14380.74, y=80.00, z=-11685.36], class_3222['Cantavio'/471, l='ServerLevel[world]', x=9043.41, y=4.00, z=-4525.09], class_3222['The_Hyena'/64451, l='ServerLevel[world]', x=-1022.32, y=21.00, z=5692.10], class_3222['Lirandil'/140067, l='ServerLevel[world]', x=-734.03, y=64.00, z=6000.35], class_3222['LennoxLx3'/64590, l='ServerLevel[world]', x=-769.25, y=112.23, z=6337.69], class_3222['The_Foot_Ninja'/143716, l='ServerLevel[world]', x=1452.92, y=64.00, z=-1408.73], class_3222['Hauntedkis'/33826, l='ServerLevel[world]', x=14.80, y=64.00, z=5308.11], class_3222['Kromanco'/145260, l='ServerLevel[world]', x=-708.40, y=64.00, z=6017.19]]
	Data Packs: vanilla, fabric, darkrpg_quests, darkrpg_recipes, darkspawn_datapack, disable_crafting_recipes, more_gems, origin_noglin_custom, origin_sculked_magpie, pfm, simplyswords, welcome, castleblocks, epic_knights, file/darkstarter_datapack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)```

**Comment by mariumbacchus** [comment]
Thanks for the heads up, has been fixed now, will be live in next patch.
