### ISSUE TITLE
the soulsweapons mod. The error message indicates that there's a NoSuchMethodError occurring in the ChaosSet class within the soulsweaponry mod.(Sinytra Connector mod )(gecklib forge)Cannot find makeRenderer method.

### ISSUE THREAD

**Issue by 1963915695** [mariumbacchus/Soulslike-Weaponry#90]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-02-08 00:38:07
Description: Initializing game

net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'soulsweapons'!
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23353!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$ecm001$connectormod$earlyInit(Minecraft.java:15923) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin from mod alexscaves,pl:mixin:APP:amecsapi.mixins.json:MixinMinecraftClient from mod amecsapi,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod connectorextras_geckolib_fabric_compat,pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod connectorextras_architectury_bridge,pl:mixin:APP:torohealth.mixins.json:MixinMinecraft from mod torohealth,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin from mod itemphysic,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin from mod cgm,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:dsurround.mixins.json:events.MixinMinecraftClient from mod dsurround,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:kirin.mixin.json:MixinMinecraftClient from mod kirin,pl:mixin:APP:betterend.mixins.client.json:MinecraftClientMixin from mod betterend,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.MinecraftMixin from mod embeddiumplus,pl:mixin:APP:embeddiumplus.mixin.json:frames.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft from mod railways,pl:mixin:APP:bclib.mixins.client.json:MinecraftMixin from mod bclib,pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod connectorextras_modmenu_bridge,pl:mixin:APP:bobby.mixins.json:MinecraftClientMixin from mod bobby,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod rubidium_extra,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:soulsweapons.mixins.json:MinecraftClientMixin from mod soulsweapons,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin from mod quark,pl:mixin:APP:spruceui.mixins.json:MinecraftClientMixin from mod spruceui,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin from mod alexscaves,pl:mixin:APP:amecsapi.mixins.json:MixinMinecraftClient from mod amecsapi,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod connectorextras_geckolib_fabric_compat,pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod connectorextras_architectury_bridge,pl:mixin:APP:torohealth.mixins.json:MixinMinecraft from mod torohealth,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin from mod itemphysic,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin from mod cgm,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:dsurround.mixins.json:events.MixinMinecraftClient from mod dsurround,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:kirin.mixin.json:MixinMinecraftClient from mod kirin,pl:mixin:APP:betterend.mixins.client.json:MinecraftClientMixin from mod betterend,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.MinecraftMixin from mod embeddiumplus,pl:mixin:APP:embeddiumplus.mixin.json:frames.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft from mod railways,pl:mixin:APP:bclib.mixins.client.json:MinecraftMixin from mod bclib,pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod connectorextras_modmenu_bridge,pl:mixin:APP:bobby.mixins.json:MinecraftClientMixin from mod bobby,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod rubidium_extra,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:soulsweapons.mixins.json:MinecraftClientMixin from mod soulsweapons,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin from mod quark,pl:mixin:APP:spruceui.mixins.json:MinecraftClientMixin from mod spruceui,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?] {}
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'soulsweapons'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23353!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 24 more
Caused by: java.lang.NoSuchMethodError: 'java.util.function.Supplier software.bernie.geckolib.animatable.GeoItem.makeRenderer(software.bernie.geckolib.animatable.GeoItem)'
	at net.soulsweaponry.items.ChaosSet.<init>(ChaosSet.java:51) ~[%5BMarium-soulslike-weaponry-1.0.2-1.20-fabric_mapped_srg_1.20.1.jar%231001!/:?] {re:classloading}
	at net.soulsweaponry.registry.ItemRegistry.<clinit>(ItemRegistry.java:56) ~[%5BMarium-soulslike-weaponry-1.0.2-1.20-fabric_mapped_srg_1.20.1.jar%231001!/:?] {re:mixin,re:classloading}
	at net.soulsweaponry.SoulsWeaponry.onInitialize(SoulsWeaponry.java:57) ~[%5BMarium-soulslike-weaponry-1.0.2-1.20-fabric_mapped_srg_1.20.1.jar%231001!/:?] {re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23353!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.36+1.20.1.jar%23348!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23353!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$ecm001$connectormod$earlyInit(Minecraft.java:15923) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin from mod alexscaves,pl:mixin:APP:amecsapi.mixins.json:MixinMinecraftClient from mod amecsapi,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod connectorextras_geckolib_fabric_compat,pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod connectorextras_architectury_bridge,pl:mixin:APP:torohealth.mixins.json:MixinMinecraft from mod torohealth,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin from mod itemphysic,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin from mod cgm,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:dsurround.mixins.json:events.MixinMinecraftClient from mod dsurround,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:kirin.mixin.json:MixinMinecraftClient from mod kirin,pl:mixin:APP:betterend.mixins.client.json:MinecraftClientMixin from mod betterend,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.MinecraftMixin from mod embeddiumplus,pl:mixin:APP:embeddiumplus.mixin.json:frames.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft from mod railways,pl:mixin:APP:bclib.mixins.client.json:MinecraftMixin from mod bclib,pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod connectorextras_modmenu_bridge,pl:mixin:APP:bobby.mixins.json:MinecraftClientMixin from mod bobby,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod rubidium_extra,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:soulsweapons.mixins.json:MinecraftClientMixin from mod soulsweapons,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin from mod quark,pl:mixin:APP:spruceui.mixins.json:MinecraftClientMixin from mod spruceui,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin from mod alexscaves,pl:mixin:APP:amecsapi.mixins.json:MixinMinecraftClient from mod amecsapi,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod connectorextras_geckolib_fabric_compat,pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod connectorextras_architectury_bridge,pl:mixin:APP:torohealth.mixins.json:MixinMinecraft from mod torohealth,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin from mod itemphysic,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin from mod cgm,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:dsurround.mixins.json:events.MixinMinecraftClient from mod dsurround,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:kirin.mixin.json:MixinMinecraftClient from mod kirin,pl:mixin:APP:betterend.mixins.client.json:MinecraftClientMixin from mod betterend,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.MinecraftMixin from mod embeddiumplus,pl:mixin:APP:embeddiumplus.mixin.json:frames.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft from mod railways,pl:mixin:APP:bclib.mixins.client.json:MinecraftMixin from mod bclib,pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod connectorextras_modmenu_bridge,pl:mixin:APP:bobby.mixins.json:MinecraftClientMixin from mod bobby,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod rubidium_extra,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:soulsweapons.mixins.json:MinecraftClientMixin from mod soulsweapons,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin from mod quark,pl:mixin:APP:spruceui.mixins.json:MinecraftClientMixin from mod spruceui,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
-- Initialization --

**Comment by mariumbacchus** [comment]
You are trying to launch the mod in forge with Sinytra connector without geckolib fabric. This is also not something I can solve, this is a Sinytra connector issue.
